server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/employeedb
    username: postgres
    password: Simpat9Lga
    hikari:
      minimum-idle: 5
      auto-commit: false
      maximum-pool-size: 20
  jpa:
    generate-ddl: false
    show_sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        hbm2ddl: none
        entitymanager:
          packagesToScan: com.mastery.simplewebapp.dto
